name: ExtrilliusParkour
author: TechBug2012
description: The custom parkour plugin for Extrillius
version: 1.0
main: net.extrillius.parkour.ExtrilliusParkour

commands:
  startingpoint:
    description: Set the starting point for a created map.
  checkpoint:
    description: Set the checkpoints for a created map.
    aliases: cp
  finishpoint:
    description: Set the finish point for a created map.
  finish:
    description: Check to see if your created map is finished.

permissions:
  parkour.build:
    description: Be able to build your own Parkour maps and share them with friends
    default: op
  parkour.admin:
    description: Have access to all administration features of the plugin.
    default: op