name: Parkour
author: TechBug2012
description: A parkour plugin for Extrillius
version: 1.0
main: net.extrillius.parkour.Parkour

commands:
  create:
    description: Being creating a map
  delete:
    description: Delete a map from the config file
  startpoint:
    description: Set the starting point for a created map.
  checkpoint:
    description: Set the checkpoints for a created map.
    aliases: cp
  endpoint:
    description: Set the finish point for a created map.
  deathblock:
    description: Set the death blocks for your map
  difficulty:
    description: Set the difficulty of your map
  customvalue:
    description: Set a custom earning amount for your map.
  finish:
    description: Check to see if your created map is finished.
  join:
    description: Join a map
  leave:
    description: Leave a map

permissions:
  parkour.build:
    description: Be able to build your own Parkour maps and share them with friends
    default: op
  parkour.admin:
    description: Have access to all administration features of the plugin.
    default: op